#Naming
experiment_name      : "ISIC-EXP-14"

#Model parameter's
model_id             : 'resnet18'
full_fit             : False
debug                : False
n_folds              : 5
batch_size           : 8
num_classes          : 2
num_workers          : 4
max_epochs           : 10
learning_rate        : 1e-5
fold                 : 0
seed                 : 2024
tpr_threshold        : 0.8
image_size           : 384
dropout              : 0.5
use_old_data         : False

#Logging
wandb_log            : True
wandb_project_name   : "ISIC"
notes                : "Resnet18, added hsv channel, added dropouts"

#Files and paths
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
training_filename    : "ISIC_train_data_balanced.csv"
image_path           : '${data_dir}/train-image.hdf5'
train_code_file      : "main.py"
config_file          : "config.yaml"
image_file_2024      : '${data_dir}/train-image.hdf5'
image_file_2020      : '${data_dir}/images_maliganant_2020.hdf5'
image_file_2019      : '${data_dir}/images_maliganant_2019.hdf5'


