#Naming
experiment_name      : "ISIC-EXP-1"

#Model parameter's
model_id             : 'efficientnet_b0'
full_fit             : False
debug                : False
n_folds              : 5
batch_size           : 128
num_classes          : 2
num_workers          : 4
max_epochs           : 5
learning_rate        : 1e-3
fold                 : 0

#Logging
wandb_log            : True
wandb_project_name   : "ISIC"
notes                : "First experiment of the competition"

#Files and paths
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
training_filename    : "ISIC_train_data.csv"
train_images         : '/train-image.hdf5'
train_code_file      : "experiment.py"
config_file          : "config.yaml"


