#Naming
experiment_name      : "ISIC-EXP-2"

#Model parameter's
model_id             : 'resnet18'
full_fit             : False
debug                : False
n_folds              : 5
batch_size           : 32
num_classes          : 2
num_workers          : 4
max_epochs           : 3
learning_rate        : 1e-5
fold                 : 0
seed                 : 2024
tpr_threshold        : 0.8
image_size           : 384
dropout              : 0.5

#Logging
wandb_log            : True
wandb_project_name   : "ISIC"
notes                : "First experiment of the competition"

#Files and paths
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
training_filename    : "ISIC_train_data.csv"
image_path           : '${data_dir}/train-image.hdf5'
train_code_file      : "main.py"
config_file          : "config.yaml"


