experiment_name      : "ISIC-EXP-1"
training_filename    : "ISIC_train_data.csv"
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
train_images         : '/train-image.hdf5'
model_id             : 'efficientnet_b0'
n_folds              : 5
batch_size           : 128
num_classes          : 2
num_workers          : 4
max_epochs           : 5
learning_rate        : 1e-3



