#Naming
experiment_name      : "test_wandb_table"

#Model parameter's
model_id             : 'efficientnet_b0'
full_fit             : False
debug                : False
n_folds              : 5
batch_size           : 64
num_classes          : 2
num_workers          : 4
max_epochs           : 1
learning_rate        : 1e-5
fold                 : 0
seed                 : 2024
tpr_threshold        : 0.8
image_size           : 312

#Logging
wandb_log            : True
wandb_project_name   : "ISIC"
notes                : "balanced dataset and 80 epochs"

#Files and paths
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
training_filename    : "ISIC_train_data_balanced.csv"
image_path           : '${data_dir}/train-image.hdf5'
train_code_file      : "main.py"
config_file          : "config_efficientnet.yaml"


