#Naming
experiment_name      : "ISIC-EXP-18"

#Model parameter's
model_id             : 'convnextv2_atto.fcmae'
full_fit             : False
debug                : False
n_folds              : 5
batch_size           : 64
num_classes          : 2
num_workers          : 4
max_epochs           : 10
learning_rate        : 1e-5
fold                 : 0
seed                 : 2024
tpr_threshold        : 0.8
image_size           : 312
dropout              : 0.5
use_old_data         : True
two_stage            : True
first_stage          : "ISIC-EXP-15"
num_frozen_layers    : 20


#Logging
wandb_log            : True
wandb_project_name   : "ISIC"
notes                : "freezing 34 layers,second stage,balanced dataset, 10 epochs, upsampled 2024 maliganant 10 times, added 2020, 2019 maliganant images"

#Files and paths
data_dir             : "./input"
artifacts_dir        : "./output"
output_dir           : "${artifacts_dir}/${experiment_name}"
training_filename    : "ISIC_train_data_2024_2020_2019_balanced.csv"
image_path           : '${data_dir}/train-image.hdf5'
train_code_file      : "second_stage.py"
config_file          : "config_convnext.yaml"
image_file_2024      : '${data_dir}/train-image.hdf5'
image_file_2020      : '${data_dir}/images_maliganant_2020.hdf5'
image_file_2019      : '${data_dir}/images_maliganant_2019.hdf5'
first_stage_model    : '${data_dir}/${first_stage}/full_fit/best-checkpoint.ckpt'


